package com.project.souklab.model;

public enum AuditLogAction {
    EMAIL_VERIFIED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,

    ASSIGN_ROLE,
    ASSIGN_PERMISSION_BULK,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,

    APPROVE_USER,
    BAN_USER,
    TIMEOUT_USER,
    UNBAN_USER,

    APPROVE_ARTISAN,
    REJECT_ARTISAN,

    APPROVE_FORMATION,
    REJECT_FORMATION,

    RESOLVE_REPORT,
    DISMISS_REPORT
}
