package com.project.souklab.model;

public enum NotificationType {
    ACCOUNT_VALIDATED,
    ACCOUNT_REJECTED,
    ACCOUNT_SUSPENDED,
    FORMATION_APPROVED,
    FORMATION_REJECTED,
    NEW_MESSAGE,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_EXPIRED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    NEW_REPORT,
    NEW_REVIEW,
    NEW_FORMATION,
    FORMATEUR_REQUEST_SUBMITTED,
    FORMATEUR_APPROVED,
    FORMATEUR_GRANTED,
    FORMATEUR_REJECTED,
    FORMATEUR_REVOKED,
    ACCOUNT_REINSTATED
}
