-- Phase 11: Admin catalog taxonomy management permission and audit actions.
-- Grants designated administrators the ability to create, update, and delete
-- Technique, Epoque, and Region catalog entries via the admin API.

INSERT IGNORE INTO permissions (id, permission_key, description, enabled, created_at, updated_at) VALUES
    (UUID(), 'permission:admin:catalog', 'Manage catalog taxonomies (categories, subcategories, material families, materials, techniques, epoques, regions)', TRUE, CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6));

-- Keep the database audit taxonomy aligned with catalog taxonomy mutations.
ALTER TABLE audit_logs MODIFY action enum(
    'APPROVE_ARTISAN','APPROVE_FORMATION','APPROVE_USER','ASSIGN_PERMISSION_BULK','ASSIGN_ROLE',
    'BAN_USER','DISMISS_REPORT','EMAIL_VERIFIED','PASSWORD_CHANGED','PASSWORD_RESET_COMPLETED',
    'PERMISSION_GRANTED','PERMISSION_REVOKED','REJECT_ARTISAN','REJECT_FORMATION','RESOLVE_REPORT',
    'TIMEOUT_USER','UNBAN_USER','SUBSCRIPTION_GRANTED','SUBSCRIPTION_ACTIVATED','SUBSCRIPTION_CANCELED',
    'SUBSCRIPTION_REVOKED','SUBSCRIPTION_STATE_CORRECTED','PAYMENT_PAID','PAYMENT_FAILED',
    'PAYMENT_CANCELED','PAYMENT_STATE_CORRECTED','REFUND_REQUEST_REJECTED',
    'SUBSCRIPTION_PLAN_CREATED','SUBSCRIPTION_PLAN_UPDATED','SUBSCRIPTION_PLAN_DEACTIVATED',
    'ANALYTICS_REBUILD','ANALYTICS_JOB_SUBMITTED','ANALYTICS_RESULT_READ','ANALYTICS_EXPORT',
    'CATALOG_TECHNIQUE_CREATED','CATALOG_TECHNIQUE_UPDATED','CATALOG_TECHNIQUE_DELETED',
    'CATALOG_EPOQUE_CREATED','CATALOG_EPOQUE_UPDATED','CATALOG_EPOQUE_DELETED',
    'CATALOG_REGION_CREATED','CATALOG_REGION_UPDATED','CATALOG_REGION_DELETED',
    'CATALOG_CATEGORY_CREATED','CATALOG_CATEGORY_UPDATED','CATALOG_CATEGORY_DELETED',
    'CATALOG_SUBCATEGORY_CREATED','CATALOG_SUBCATEGORY_UPDATED','CATALOG_SUBCATEGORY_DELETED',
    'CATALOG_MATERIAL_FAMILY_CREATED','CATALOG_MATERIAL_FAMILY_UPDATED','CATALOG_MATERIAL_FAMILY_DELETED',
    'CATALOG_MATERIAL_CREATED','CATALOG_MATERIAL_UPDATED','CATALOG_MATERIAL_DELETED'
) NOT NULL;
