-- Extend the notification taxonomy for moderated feed lifecycle and engagement events.
ALTER TABLE notifications MODIFY type enum(
    'ACCOUNT_REINSTATED','ACCOUNT_REJECTED','ACCOUNT_SUSPENDED','ACCOUNT_VALIDATED','FORMATEUR_APPROVED',
    'FORMATEUR_GRANTED','FORMATEUR_REJECTED','FORMATEUR_REQUEST_SUBMITTED','FORMATEUR_REVOKED',
    'FORMATION_APPROVED','FORMATION_REJECTED','NEW_FORMATION','NEW_MESSAGE','NEW_REPORT','NEW_REVIEW',
    'PAYMENT_FAILED','PAYMENT_SUCCESS','SUBSCRIPTION_RENEWED','SUBSCRIPTION_EXPIRED','CHECKOUT_CREATED',
    'CHECKOUT_CANCELED','SUBSCRIPTION_RENEWAL_REMINDER','SUBSCRIPTION_MANUALLY_GRANTED','SUBSCRIPTION_REVOKED',
    'REFUND_REQUEST_UNAVAILABLE',
    'FEED_POST_SUBMITTED','FEED_POST_PUBLISHED','FEED_POST_REJECTED','FEED_POST_HIDDEN',
    'FEED_POST_LIKED','FEED_POST_COMMENTED','FEED_COMMENT_LIKED','FEED_COMMENT_REPLIED'
) DEFAULT NULL;
