ALTER TABLE audit_logs MODIFY action enum(
    'APPROVE_ARTISAN','APPROVE_FORMATION','APPROVE_USER','ASSIGN_PERMISSION_BULK','ASSIGN_ROLE',
    'BAN_USER','DISMISS_REPORT','EMAIL_VERIFIED','PASSWORD_CHANGED','PASSWORD_RESET_COMPLETED',
    'PERMISSION_GRANTED','PERMISSION_REVOKED','REJECT_ARTISAN','REJECT_FORMATION','RESOLVE_REPORT',
    'TIMEOUT_USER','UNBAN_USER','SUBSCRIPTION_GRANTED','SUBSCRIPTION_CANCELED','SUBSCRIPTION_REVOKED',
    'SUBSCRIPTION_STATE_CORRECTED','PAYMENT_STATE_CORRECTED','REFUND_REQUEST_REJECTED',
    'SUBSCRIPTION_PLAN_CREATED','SUBSCRIPTION_PLAN_UPDATED','SUBSCRIPTION_PLAN_DEACTIVATED',
    'ANALYTICS_REBUILD','ANALYTICS_JOB_SUBMITTED','ANALYTICS_RESULT_READ','ANALYTICS_EXPORT'
) NOT NULL;
